name: Build and Release ExcelToJson

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore ExcelToJson.sln

      - name: Build project
        run: msbuild ExcelToJson.sln /p:Configuration=Release

      - name: Install 7-Zip
        run: choco install 7zip -y

      - name: Verify build output
        run: |
          $path = ".\ExcelToJson\bin\Release\net8.0-windows"
          if (!(Test-Path $path)) {
            Write-Error "Build output directory does not exist: $path"
            exit 1
          }
          Get-ChildItem -Path $path -Recurse | Format-Table FullName

      - name: Create archive with 7-Zip
        run: |
          $source = ".\ExcelToJson\bin\Release\net8.0-windows"
          $destination = ".\ExcelToJson\ExcelToJson.zip"
          
          # Создаем архив, сохраняя структуру папок
          7z a $destination "$source\*" -r -mx=9 -x!*.pdb -x!*.xml -x!*.config
          
          # Проверяем размер архива
          if (!(Test-Path $destination)) {
            Write-Error "Archive was not created"
            exit 1
          }
          Write-Output "Archive created successfully:"
          dir $destination

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          files: .\ExcelToJson\ExcelToJson.zip
          draft: false
          prerelease: false
          generate_release_notes: true
