name: Build and Release ExcelToJson

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore ExcelToJson.sln

      - name: Build project
        run: msbuild ExcelToJson.sln /p:Configuration=Release

      - name: Install 7-Zip
        run: choco install 7zip -y

      - name: Verify build output
        run: |
          $buildPath = "$env:GITHUB_WORKSPACE\ExcelToJson\bin\Release\net8.0-windows"
          Write-Output "Build path: $buildPath"
          Get-ChildItem -Path $buildPath -Recurse | Format-Table FullName

      - name: Create archive
        run: |
          $source = "$env:GITHUB_WORKSPACE\ExcelToJson\bin\Release\net8.0-windows"
          $destination = "$env:GITHUB_WORKSPACE\ExcelToJson\ExcelToJson.zip"
          $tempDir = "$env:RUNNER_TEMP\publish"
          New-Item -ItemType Directory -Path $tempDir -Force
          Copy-Item "$source\*" $tempDir -Recurse -Exclude "*.pdb","*.xml","*.config"
          7z a "$destination" "$tempDir\*" -r -mx=9
          7z l "$destination"
          $archive = Get-Item $destination
          Write-Output "Archive size: $($archive.Length) bytes"
          if ($archive.Length -lt 1024) {
              Write-Error "Archive is too small - likely empty"
              exit 1
          }

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          files: |
            ExcelToJson/ExcelToJson.zip
          draft: false
          prerelease: false
          generate_release_notes: true
